name: Automerge Dependabot PRs
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Automerge
        uses: peter-evans/automerge-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash

